name: buildWindows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: cmake_config
        run: |
          apt install mingw-w64 -y
          mkdir build && cd build
          cmake .. -DCMAKE_CXX_COMPILER=x86_64-w64-mingw-g++-posix
      - name: make
        run: cmake --build build
      - name: remove useless files
        run: rm -rf .git; rm -rf $(find . | grep ".cpp") ; rm -rf $(find . | grep ".h"); rm -rf $(find . | grep ".hpp")
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.0
        with:
          name: epp-windows-(dev-0.1.1)
          path: build
