name: epp_build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: prepare
        run: | 
            sudo apt install mingw-w64 -y
            sudo apt install cmake -y
      - name: cmake_config
        run: |
            mkdir build && cd build
            ls
      - name: make
        run: cmake --build .
      - name: remove useless files
        run: rm -rf .git; rm -rf $(find . | grep ".cpp") ; rm -rf $(find . | grep ".h"); rm -rf $(find . | grep ".hpp")
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.0
        with:
          name: build-all
          path: .